### PR TITLE
Fix issue where jsx line breaks were not respecting quote config.

### LINKED ISSUE #300: Inserted {" "} when breaking JSX up with whitespace always uses double quotes
**Describe the bug**

Even with `alwaysSingle` / `preferSingle` for quote style + jsx quote style, an inserted `{" "}` text node that happens when breaking up jsx text will always use double quotes, when it should actually use single quotes. It should probably follow `quoteStyle` and not `jsx.quoteStyle`, since I think the latter is more for attributes etc rather than the contents of a JSX expression, which is regular JS / TS and no longer in a JSX context. 

Note that this doesn't happen for regular quoted expressions such as:
```tsx
() => (
  <>
    {' '}
  </>
)
```
which do end up being formatted correctly as per `quoteStyle`. It's only the automatic insertion that's using the wrong quotes. 

dprint-plugin-typescript version: 0.56.2

**Input Code**

```tsx
() => (
    <>
        This is a really long line that should be broken up, with an space: {value} but the space should use single quotes
    </>
)
```

**Expected Output**

```tsx
(() => (
    <>
        This is a really long line that should be broken up, with an space:{' '}
        {value} but the space should use single quotes
    </>
));

```

**Actual Output**

```tsx
(() => (
    <>
        This is a really long line that should be broken up, with an space:{" "}
        {value} but the space should use single quotes
    </>
));
```

[Playground link](https://dprint.dev/playground/#code/BQSgBAvAfGwFBkWAPFBSMBUAWBLAzmAWAIZgBOApiQDY0CeYNA9gHYDmTurlYALthJ8w+bMwCuNACZgARr1nlmAa0qsw4gA4AaMAHdcA0uvyaSAY0oAuMAG8AbrXGUAvnPHCBvUxe9jJMuL43tzsNLwAjuLMfJT46IjIAPRoIEA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgA4AGAGnCgTUXg1Ux3wBYyJIBXAZ0QBUBDAIw54wAM17QuLKFwC2sAMIB7aIvhD8kAA4AnRCMTbIUyAEc2ijIgDKGAJ7REwyOIDuvWxysIA5g6PlIACsOAA8AOjMLazs-DR09Ay94X0djJBcAGQREAGlKJ2gRf1ZORAAhbV4AY0R1KBcsagA5CySUrKRiqH5KmoAFRQ5YDFhVJw5eGUQOxABVeAcODgAJXmSfLsgh5IcyxTRbAaGRsY0ZXgQMC-hNpBCMJRptZQAxFRcj4dGbjTuMGc2GEqsDgySUMnOdUgqmgtgAsmxoCMAcZFJoDLwMIptJ8Tj8oH8UQF4vptKt1slhGIJIhjCTEj4HAD8NTJAFeNpni4Xmx4FU8WFSn0OdRsLVak5zpdrpt+AgObYAKIheJLb5hUGIPoGZWqoanUTiNmsYLhGSI5HZYW6NTCIFsWkBKYyfg6lW6NWqDVWt1675Uo2O1h2dFZSyVaBhLiaDmY7F5eBocaIORKFQ3YzUNgyAAiiCq0FjAudru0VhjVQ2Z2uVwQmw4FesbE5il5aB8fWe6O0Iwl+HtQagin4gXzGF1Hv18CjjaszeebY7XYMvbqA9RI7Hwow4enDeqTZbi+SnbRK9gfbA64CIemwwxkf3NTnR8TS7PPYva+0DuMcvgCoTrUU4zgeL4Lm+yRlMMLiwFwACCibwdowxYFMIxVAA8t2caGP2P6DpAVSKBCoozGEIjYs+jbwSI4ZWIWHCNN+v4BMRaj2vy2KgTUZR6NiWoijQzGXqyhHsRwnFYto3C2OiPGILR4ZNIgLg5IgtguNiSYsoGxgSVJXjeABGDNogClKQYKlqRpWnaDpho0sYaCKMgWAgtEmIpqKFl0QYbkeepmnaXaBGZiq2IYHmBZFuqT6HhB7bJE0kyIGguqRSxhGUdoACS8A2F5Uw0L54YvPGtkhfhrGsDlmEiIVljFRgpUGOV2hBXZDnXrV2KNd5JXxZZ2jtZ1VVXmFAQ5f1zWtWWKYKMoqhZcYIi8vy3zRYWlQCvFfE5YJNpilwdRiat614kBnp7o2+0CdaooiadelTRd3xXSBQ1+SNb2qGN9kBk5ATeIgGDwVUNRLNxe38boD3CeKz1A6wsANVcTU+V94a5SI-3dZNKMyJokVbbFXrxeBraQd4KVTGguVE5loU1VApqKg4s0wwdViIIU8gqNs3h8N4DG8ExzOEWz7rAd8jy1kg2gKZTx7eB9-q6cjUDoVg+wKXdcNCcdokvawXBgxDwHQ7dsOHY9iOA8aUBXN4INoNwKaaIWlh6zbYYPhLxi3oh8AWJicXWwdaYGmdN5yYpSznuTEcCWrBo9fU7kODNmM0d9AUOHjAcBLAxkCS0VDgs17v3E4aA6JcAC0Jch7omzNwJLweZXorVxgtf1zQTel7oDciB5kAgAAviAQA/language/typescript)

I might take a look at this one today if I can find the time...

### PR DESCRIPTION
**Pull request by ryan-rushton**
The quote characters for jsx line breaks were hard coded to use double quotes. This PR uses the configured QuoteStyle to create the empty string.

Fixes #300

### CODE REVIEW

File: src/parsing/parser.rs [hunk 1]
```diff
@@ -7941,11 +7941,18 @@ fn jsx_space_separator(previous_node: &Node, current_node: &Node, context: &Cont
...
+      QuoteStyle::PreferSingle | QuoteStyle::AlwaysSingle => "\'".to_string()
+    };
+  }
+
   fn jsx_force_space_with_newline_if_either_node_multi_line(previous_node: &Node, current_node: &Node, context: &Context) -> PrintItems {
     let previous_node_info_range = get_node_info_range(previous_node, context);
     let current_node_info_range = get_node_info_range(current_node, context);
     let spaces_between_count = node_helpers::count_spaces_between_jsx_children(previous_node, current_node, &context.module);
-    let jsx_space_expr_text = format!("{{\"{}\"}}", " ".repeat(spaces_between_count));
+    let jsx_space_expr_text = format!("{{{}{}{}}}", get_quote_char(context), " ".repeat(spaces_between_count), get_quote_char(context));
```
Comment (ryan-rushton) [inline src/parsing/parser.rs:7955]: Was tempted to pull this out into a `fn` but it wasn't before so I left it. Happy to pull it out should you want to.

File: src/parsing/parser.rs [hunk 2]
```diff
@@ -7941,11 +7941,18 @@ fn jsx_space_separator(previous_node: &Node, current_node: &Node, context: &Cont
     }
   }
 
+  fn get_quote_char(context: &Context) -> String {
+    return match context.config.quote_style {
+      QuoteStyle::PreferDouble | QuoteStyle::AlwaysDouble => "\"".to_string(),
+      QuoteStyle::PreferSingle | QuoteStyle::AlwaysSingle => "\'".to_string()
```
Comment (declanvong) [inline src/parsing/parser.rs:7947]:
```suggestion
      QuoteStyle::PreferSingle | QuoteStyle::AlwaysSingle => "'".to_string()
```

**Comment by dsherret** [comment]
Looks good. Thanks @ryan-rushton!

File: src/parsing/parser.rs (hunk 1 above)
Comment (dsherret) [reply src/parsing/parser.rs:7955]: That's ok! It's a minor thing. I'm going to do this after merge to expedite a release.
