### PR TITLE
fix: comments on line above case should not get extra newline when has preceding blank line

### LINKED ISSUE #406: Comment above case gets extra newline
**Describe the bug**

dprint-plugin-typescript version: 0.71.2

Comments in the middle of cases get an extra newline before them.

**Input Code**

```ts
switch (foo) {
    // Types
    case SyntaxKind.A:
        return 1234;
    
    // Values
    case SyntaxKind.B:
        return 1234;
}
```

**Expected Output**

```ts
switch (foo) {
  // Types
  case SyntaxKind.A:
    return 1234;

  // Values
  case SyntaxKind.B:
    return 1234;
}
```

**Actual Output**

```ts
switch (foo) {
  // Types
  case SyntaxKind.A:
    return 1234;

  // Values

  case SyntaxKind.B:
    return 1234;
}
```

### PR DESCRIPTION
**Pull request by dsherret**
This is a bit of a hack because I'd rather have the case generate its leading comments that it "owns", but doing so would mean the case comment ownership rules would be spread around in multiple places so this is a lot easier.

Closes #406

### CODE REVIEW

File: src/generation/generate.rs [hunk 1]
```diff
@@ -7844,12 +7853,7 @@ fn gen_conditional_brace_body<'a>(opts: GenConditionalBraceBodyOptions<'a>, cont
   let end_statements_lc = LineAndColumn::new("endStatements");
   let header_trailing_comments = get_header_trailing_comments(opts.body_node, context);
   let body_should_be_multi_line = get_body_should_be_multi_line(opts.body_node, &header_trailing_comments, context);
-  let should_use_new_line = get_should_use_new_line(
```
Comment (jakebailey) [inline src/generation/generate.rs:7847]: Oops, I forgot to format things on my PR, sorry! (ironic?)

Comment (dsherret) [reply src/generation/generate.rs:7847]: No, that's ok. I don't enforce formatting on the CI 😄
