### PR TITLE
fix: `arguments.spaceAround` not adding spaces when an arrow function is the only argument

### LINKED ISSUE #581: spaceAround fails for arrow functions inside parens
**Describe the bug**
"spaceAround" does not work when an arrow function is the only statement inside parens.

dprint-plugin-typescript version: 0.88.3

**Config**
```json
{
  "spaceAround": true
}
```

**Input Code**

```ts
const somePromise: Promise = new Promise()
somePromise.then(() => console.log("Promise is done"))
```

**Expected Output**

```ts
const somePromise: Promise = new Promise();
somePromise.then( () => console.log( "Promise is done" ) );
```

**Actual Output**

```ts
const somePromise: Promise = new Promise();
somePromise.then(() => console.log( "Promise is done" ));
```

### PR DESCRIPTION
**Pull request by Thristhart**
Fixes #581

The `if !force_use_new_lines && nodes.len() == 1 && is_arrow_function_with_expr_body(nodes[0])` path wasn't considering the `space_around` option. I'm not sure if this is the most correct way to fix this problem, but it at least works on my codebase and passes the tests.

### CODE REVIEW

File: src/generation/generate.rs [hunk 1]
```diff
@@ -7270,6 +7273,7 @@ where
             Some(is_different_line && is_different_start_line_indentation)
           }),
           Signal::NewLine.into(),
+          if space_around { Signal::SpaceIfNotTrailing.into() } else { "".into() },
```
Comment (dsherret) [inline src/generation/generate.rs:7276]:
```suggestion
          if space_around { Signal::SpaceIfNotTrailing.into() } else { PrintItems::new() },
```

**Review by dsherret — APPROVED** [review]
Thanks!
